language: python
sudo: false
python:
  - '3.4'
  - '3.3'
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=rinse setup.py test
after_success:
  - coveralls
